stopWords = {"!": 0, "?": 0, "à": 0, "a": 0, "aussi": 0, "c": 0, "ça": 0, "car": 0, "ce": 0, "cela": 0, "ces": 0,
             "cette": 0, "ceux": 0, "cependant": 0, "chaque": 0, "ci": 0, "comme": 0, "comment": 0, "d": 0,
             "dans": 0,
             "de": 0, "des": 0, "du": 0, "dedans": 0, "dehors": 0, "depuis": 0, "devrait": 0, "doit": 0, "donc": 0,
             "dos": 0, "début": 0, "elle": 0, "elles": 0, "en": 0, "est": 0, "et": 0, "eu": 0, "fait": 0,
             "faites": 0,
             "font": 0, "hors": 0, "ici": 0, "il": 0, "ils": 0, "j": 0, "je": 0, "juste": 0, "l": 0, "la": 0,
             "le": 0,
             "les": 0, "leur": 0, "là": 0, "lui": 0, "lorsque": 0, "m": 0, "ma": 0, "me": 0, "maintenant": 0,
             "mais": 0,
             "mes": 0, "mine": 0, "moins": 0, "mon": 0, "mot": 0, "même": 0, "n": 0, "ne": 0, "ni": 0, "nommés": 0,
             "notre": 0, "nous": 0, "on": 0, "ou": 0, "où": 0, "par": 0, "parce": 0, "pas": 0, "peut": 0, "peu": 0,
             "plupart": 0, "pour": 0, "pourquoi": 0, "qu": 0, "quand": 0, "que": 0, "quel": 0, "quelle": 0,
             "quelles": 0, "quels": 0, "quelques": 0, "qui": 0, "s": 0, "sa": 0, "se": 0, "sans": 0, "ses": 0,
             "seulement": 0, "si": 0, "sien": 0, "son": 0, "sont": 0, "sous": 0, "soyez": 0, "sujet": 0, "sur": 0,
             "ta": 0, "tandis": 0, "tellement": 0, "tels": 0, "tes": 0, "ton": 0, "tu": 0, "un": 0, "une": 0,
             "votre": 0, "vous": 0, "vu": 0, "y": 0}